#!/bin/sh

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."

curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  fancy_echo "ensure /usr/local/bin is part of set -gx PATH"

  export PATH="/usr/local/bin:$PATH"
fi

brew bundle --file=- <<EOF
# Taps
tap "thoughtbot/formulae"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
tap "homebrew/cask-fonts"
# tap "railwaycat/emacsmacport"
tap "borkdude/brew"
tap "mergestat/mergestat"
tap "homebrew/cask-versions"
tap "homebrew/cask-drivers"

# Unix
brew "fish"
brew "rcm"
brew "wget"
brew "telnet"
brew "universal-ctags", args: ["HEAD"]
brew "git"
brew "svn"
brew "openssl"
brew "reattach-to-user-namespace"
brew "rg"
brew "tmux"
brew "watchman"
brew "zsh"
brew "rbenv"
brew "fzf"
brew "tldr"
brew "jq"
brew "plantuml"
brew "direnv"
brew "graphviz"
brew "cmake"
brew "htop"
brew "fd"
brew "tree"
brew "ack"
brew "awscli"
brew "mergestat"

# Image manipulation
brew "imagemagick"

# dev tools
brew "libyaml" # should come after openssl
brew "coreutils"
brew "borkdude/brew/babashka"
brew "hydra"
brew "yarn"
brew "go"
brew "hugo"
brew "pandoc"
brew "kubectx"
cask "docker"
cask "sequel-ace"
cask "lens"
cask "sourcetree"

# java
cask "temurin"
brew "gradle"
brew "mvnvm"

# Databases
# brew "postgres", restart_service: :changed
brew "redis", restart_service: :changed
brew "mysql", restart_service: :changed

# Editors
# brew "emacs-mac", args: ["with-modules", "with-rsvg", "with-natural-title-bar", "with-modern-icon", "with-starter", "with-imagemagick"]
brew "nvim"
cask "jetbrains-toolbox"
cask "sublime-text"
cask "visual-studio-code"

# Fonts
cask "font-fira-mono-nerd-font"
cask "font-fira-mono-for-powerline"
cask "font-fira-code"

# Applications
cask "ngrok"
cask "gpg-suite"
cask "aws-vault"
cask "rectangle"
cask "iterm2"
cask "appcleaner"
cask "google-chrome"
cask "iterm2"
cask "sublime-merge"
cask "slack"
cask "the-unarchiver"
cask "macs-fan-control"
cask "alfred"
cask "whatsapp"
cask "spotify"
cask "mpv"
cask "insomnia"
cask "lunar"
cask "authy"
cask "bitwarden"
cask "firefox" 
cask "audacity"
# cask "postico"

# Drivers
cask "logitech-options"
EOF

fancy_echo "All brew installations complete!!"
