#!/bin/sh

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."

  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
  
  fancy_echo "ensure /usr/local/bin is part of set -gx PATH"
  
  export PATH="/usr/local/bin:$PATH"
fi

brew bundle --file=- <<EOF
# Taps
tap "thoughtbot/formulae"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
tap "homebrew/cask-fonts"
tap "railwaycat/emacsmacport"
tap "buo/cask-upgrade"
tap "wallix/awless"
tap "borkdude/brew"

# Unix
brew "fish"
brew "rcm"
brew "wget"
brew "telnet"
brew "universal-ctags", args: ["HEAD"]
brew "git"
brew "svn"
brew "openssl"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "rg"
brew "tmux"
brew "watchman"
brew "zsh"
brew "rbenv"
brew "fzf"
brew "tldr"
brew "jq"
brew "plantuml"
brew "direnv"
brew "graphviz"
brew "cmake"
brew "htop"
brew "fd"
brew "tree"
brew "ack"
brew "awscli"
brew "awless"

# Image manipulation
brew "imagemagick"

# dev tools
brew "libyaml" # should come after openssl
brew "coreutils"
brew "borkdude/brew/babashka"
brew "hydra"
brew "yarn"
brew "go"
brew "hugo"
brew "pandoc"
cask "corretto"
cask "nosql-workbench-for-amazon-dynamodb"
cask "postico"
cask "google-cloud-sdk"
cask "docker"

# Databases
brew "postgres", restart_service: :changed
brew "redis", restart_service: :changed

# Editors
brew "emacs-mac", args: ["with-modules", "with-rsvg", "with-natural-title-bar", "with-modern-icon", "with-starter", "with-jansson", "HEAD"]
brew "nvim"
cask "intellij-idea"
cask "jetbrains-toolbox"
cask "sublime-text"

# Fonts
cask "font-fira-mono-nerd-font"
cask "font-fira-mono-for-powerline"
cask "font-fira-code"

# Applications
cask "gpg-suite"
cask "aws-vault"
cask "spectacle"
cask "iterm2"
cask "lastpass"
cask "appcleaner"
cask "dash"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "the-unarchiver"
cask "macs-fan-control"
cask "sourcetree"
cask "alfred"
cask "whatsapp"
cask "zoomus"
cask "spotify"
cask "mpv"
cask "insomnia-designer"
EOF

fancy_echo "All brew installations complete!!"


